# Generated by Django 5.2.4 on 2025-07-09 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('social', '0008_delete_chatmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='user',
            new_name='sender',
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.community'),
        ),
    ]
