# Generated by Django 5.2.4 on 2025-07-09 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_chatmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
